"""create table to upload or insert text and files

Revision ID: 13ccf2d2d280
Revises: edef0d6d3756
Create Date: 2025-04-30 16:46:23.626894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13ccf2d2d280'
down_revision: Union[str, None] = 'edef0d6d3756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summarize_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summarize_settings_id'), 'summarize_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summarize_settings_id'), table_name='summarize_settings')
    op.drop_table('summarize_settings')
    # ### end Alembic commands ###
